### ISSUE TITLE
Adapter for class rather than property

### ISSUE THREAD

**Issue by kh-bakhtiari** [rharter/auto-value-parcel#100]
How can I register a TypeAdapter to a class rather than a property so I don't have to register it everywhere I use the class as a property.

**Comment by rharter** [comment]
That's a function of Moshi, just register the adapter for that class when
you get your Moshi instance.

**Comment by hister** [comment]
I meant com.ryanharter.auto.value.parcel.TypeAdapter for parcelable not for gson or mushi.

or maybe i misunderstood something ?

**Comment by rharter** [comment]
Sorry, I've got a lot of these similar projects :)

Unfortunately, that's not something you can do.  Unlike Gson and Moshi, Android's Parcelable doesn't have a central registry that resolves types, so there's nothing to register adapters with.  Each parcel/unparcel operation is completely isolated.

I think it's too burdensome to try to introduce our own registry, as there are a lot of complications around multiple module projects, package scope, etc.

**Comment by rharter** [comment]
An option for something like this would be to wrap the type in something parcelable.  Otherwise, there's no way to register a type adapter for all classes, since they won't be able to be unparcelled.

**Comment by hister** [comment]
what if we register the adapter to class and keep it as an private static property and in its creator we call the given adapter ?

P.S. for now I'm wrapping the class as you suggested but I feel that adapter per class could be implemented without too much heavy work

**Comment by rharter** [comment]
@hister `what if we register the adapter to class...` <- register the adapter with what?  There is no central manager like there is for Moshi and Gson.

There would need to be something registered at compile time, like a processor argument, that overrides the default type adapter for a type.  That's non-trivial and poses potential problems for multi-module projects, or library dependencies, but it is technically doable.

**Comment by hzsweers** [comment]
Nothing more to do here
