### ISSUE TITLE
Not support `Converting back to a builder` of AutoValue

### ISSUE THREAD

**Issue by atomd** [rharter/auto-value-parcel#11]
Hi,
When I want to convert back to a builder, I wil get an error: 

`
Error:(26, 29) error: AutoValue property toBuilder is not primitive, Parcelable, or Serializable.
`

**Comment by rharter** [comment]
This is an error in AutoValue and is being tracked by issue 281: https://github.com/google/auto/issues/281

The workaround for now is to simply implement your `toBuilder` method to `return new AutoValue_Foo.Builder(this);`

**Comment by Rainer-Lang** [comment]
@rharter Thanks for your solution/workaround. :+1:
