### ISSUE TITLE
How to used Generic?

### ISSUE THREAD

**Issue by tpnet** [rharter/auto-value-parcel#110]
My User Bean:
`
@AutoValue
public abstract class User<A,B,C> implements Parcelable{

    abstract String name();
    abstract String addr();
    abstract int age();
    abstract String gender();
    abstract String hobby();
    abstract String sign();

    abstract A data();
    abstract List<B> dataList();
    abstract Map<String, List<C>> dataMap();

    //需要注解自定义的TypeAdapter
    @ParcelAdapter(DateTypeAdapter.class)
    public abstract Date date();

    public static <A, B, C> TypeAdapter<User<A, B, C>> typeAdapter(Gson gson,
                                                                  TypeToken<? extends User<A, B, C>> typeToken) {
        return new AutoValue_User.GsonTypeAdapter(gson, typeToken);
    }

}
`

When i make module, error:
`Error:(30, 16) : AutoValue property data is not a supported Parcelable type.`

**Comment by JakeWharton** [comment]
Use `A extends Parcelable` or some other generic bound that ensures the
type can be parceled.

**Comment by tpnet** [comment]
thanks， But when i used the @GsonTypeAdapterFactory , AutoValue  generate AutoValueGson_UserAdapterFactory not Generic,   build error: not found class A.....

Foo.java:
```
@AutoValue
public abstract class Foo<A extends Parcelable,B extends Parcelable,C extends Parcelable> implements Parcelable{


    abstract String bar();
    @SerializedName("Baz") abstract String baz();
    abstract int quux();
    abstract String with_underscores();

    abstract A data();
    abstract List<B> dataList();
    abstract Map<String, List<C>> dataMap();
 
    @ParcelAdapter(DateTypeAdapter.class)
    public abstract Date date();

    public static <A extends Parcelable,B extends Parcelable,C extends Parcelable> Foo create
            (String bar, String baz, int quux, String with_underscores, Date date,A data,List<B> dataList,Map<String, List<C>> dataMap) {
        return new AutoValue_Foo(bar, baz, quux, with_underscores,data,dataList,dataMap, date);
    }

 
    public static <A extends Parcelable,B extends Parcelable,C extends Parcelable> TypeAdapter<Foo<A, B, C>> typeAdapter(Gson gson,
                                                                  TypeToken<? extends Foo<A, B, C>> typeToken) {
        return new AutoValue_Foo.GsonTypeAdapter(gson, typeToken);
    }
 
}
```

UserAdapterFactory.java:

```
@GsonTypeAdapterFactory
public abstract class UserAdapterFactory <A extends Parcelable,B extends Parcelable,C extends Parcelable>  implements TypeAdapterFactory {
    

    public static  TypeAdapterFactory create() {
        return new  AutoValueGson_UserAdapterFactory();
    }

}
```


when i build the module，error: not found A,not found B...
```
public final class AutoValueGson_UserAdapterFactory extends UserAdapterFactory {
  @Override
  @SuppressWarnings("unchecked")
  public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
    Class<T> rawType = (Class<T>) type.getRawType();
    if (Foo.class.isAssignableFrom(rawType)) {
      return (TypeAdapter<T>) Foo.typeAdapter(gson, (TypeToken<? extends Foo<A, B, C>>) type);
    } else if (User.class.isAssignableFrom(rawType)) {
      return (TypeAdapter<T>) User.typeAdapter(gson);
    } else {
      return null;
    }
  }
}
```

**Comment by ZacSweers** [comment]
This seems like it's a bug report for auto-value-gson, not parcel
