### ISSUE TITLE
An error happened, when my javabean implements Parcelable!

### ISSUE THREAD

**Issue by CzwAthou** [rharter/auto-value-parcel#111]
An error happened, when my javabean implements Parcelable!

the code about my javabean is: 
![image](https://cloud.githubusercontent.com/assets/5925762/24038435/515516f4-0b3c-11e7-977a-f64d0c71952a.png)

when I compile the module, an error happened, the detail info is:
Extension com.ryanharter.auto.value.parcel.AutoValueParcelExtension wants to consume a property that does not exist: writeToParcel  !

I can't find any error in my code!  help me!

**Comment by rharter** [comment]
What version of AutoValue are you using?

**Comment by CzwAthou** [comment]
thank you!  I had resolved this issue by improving the version!

**Comment by LiHanGuang** [comment]
@rharter @CzwAthou 

How to fix  "not exist: writeToParcel " ?
