### ISSUE TITLE
Is dependency correctly described?

### ISSUE THREAD

**Issue by vogella** [rharter/auto-value-parcel#114]
The Readme.md says that we should add:

apt 'com.ryanharter.auto.value:auto-value-parcel:0.2.5'

which results in an system error in my newly created project. The following works for me:

annotationProcessor 'com.ryanharter.auto.value:auto-value-parcel:0.2.5'

For full build.gradle see details:

<details>

apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.vogella.android.autovalue"
        minSdkVersion 24
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    testCompile 'junit:junit:4.12'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    annotationProcessor 'com.google.auto.value:auto-value:1.4'
    annotationProcessor 'com.ryanharter.auto.value:auto-value-parcel:0.2.5'
    provided 'com.jakewharton.auto.value:auto-value-annotations:1.4'
}

</details>

**Comment by rharter** [comment]
Apt works if you use the mentioned android-apt plugin. Using the newer
plugins allow you to use annotationProcessor.
