### ISSUE TITLE
Cannot use Builder with custom Parcelable type ?

### ISSUE THREAD

**Issue by Benlenem** [rharter/auto-value-parcel#117]
Hi,

I'm not able to compile when using `implements Parcelable` with an `@AutoValue.Builder` and a custom ParcelAdapter I wrote for a Joda DateTime. I got an `error: Expected a method with this signature: my.package.Foo.Builder setDescribeContents(int), or a describeContentsBuilder() method`.

I'm using auto-value 1.4.1 and parcel-adapter 0.2.5.

```package my.package;

import android.os.Parcelable;
import android.support.annotation.Nullable;
import com.google.auto.value.AutoValue;
import com.ryanharter.auto.value.parcel.ParcelAdapter;
import org.joda.time.DateTime;
import my.package.JodaDateTimeAdapter;

@AutoValue
public abstract class Foo implements Parcelable {

    @ParcelAdapter(JodaDateTimeAdapter.class)
    @Nullable
    public abstract DateTime bar();

    public static Builder builder() {
        return new AutoValue_Foo.Builder();
    }

    @AutoValue.Builder
    public abstract static class Builder {
        public abstract Builder setBar(DateTime d);
        public abstract Foo build();
    }
}
```

**Comment by JakeWharton** [comment]
Looks like an auto value bug. It should be ignoring consumed properties
from extensions.

**Comment by grandstaish** [comment]
I just tried this with the versions you mentioned and didn't have any issues

**Comment by autonomousapps** [comment]
I got a similar issue when I updated my annotation processing from using `apt` to `annotationProcessor`. Can't even build my project. Using AutoValue everywhere, as well as the FragmentArgs library.

**Comment by davidtcdeveloper** [comment]
Same situation here.
Is there any addition information required? Is there anything I can do to help?

**Comment by yuyumonwin** [comment]
Same here. Happens on Kotlin too.

**Comment by anbarasuthresnathan** [comment]
Is there any luck anyone Fixed it?

**Comment by hzsweers** [comment]
Please file a bug with auto value, as it seems unrelated here. We can revisit as necessary though

**Comment by desh-woes** [comment]
I am currently having the same issue trying to build with bazel. I get the error 

```
Expected a method with this signature: my.package.Foo.Builder.Builder setDescribeContents(int), or a describeContentsBuilder()
```

While trying to compile `implements Parcelable` with an `@AutoValue.Builder`. 

How was this issue resolved?

**Comment by desh-woes** [comment]
Actually, it seems like this does the trick. `compile 'com.ryanharter.auto.value:auto-value-parcel-adapter:0.2.9'`
