### ISSUE TITLE
ArrayList cannot be converted to ImmutableList

### ISSUE THREAD

**Issue by ashraffouad** [rharter/auto-value-parcel#118]
Hi,
I'm getting error
`Error:(18, 51) error: incompatible types: ArrayList cannot be converted to ImmutableList<String>`

When I try to rebuild this sample class from official [AutoValue sample for collection](https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#collection)

```@AutoValue
public abstract class Animal implements Parcelable {
    public abstract String name();
    public abstract int numberOfLegs();
    public abstract ImmutableList<String> countries();

    public static Builder builder() {
        return new AutoValue_Animal.Builder();
    }

    @AutoValue.Builder
    public abstract static class Builder {
        public abstract Builder setName(String value);
        public abstract Builder setNumberOfLegs(int value);
        public abstract Builder setCountries(List<String> value);
        public abstract Animal build();
    }
}
```
This class is similar to example but only three things changed:
1. Added "implements Parcelable"
2. Changed "ImmutableSet" to "ImmutableList"
3. Changed Set<String> to List<String>

This error is shown in generated class  AutoValue_Animal, method createFromParcel as below
```
final class AutoValue_Animal extends $AutoValue_Animal {
  public static final Parcelable.Creator<AutoValue_Animal> CREATOR = new Parcelable.Creator<AutoValue_Animal>() {
    @Override
    @SuppressWarnings("unchecked")
    public AutoValue_Animal createFromParcel(Parcel in) {
      return new AutoValue_Animal(
          in.readString(),
          in.readInt(),
          (ImmutableList<String>) in.readArrayList(String.class.getClassLoader())
      );
    }
    @Override
    public AutoValue_Animal[] newArray(int size) {
      return new AutoValue_Animal[size];
    }
  };

  AutoValue_Animal(String name, int numberOfLegs, ImmutableList<String> countries) {
    super(name, numberOfLegs, countries);
  }

  @Override
  public void writeToParcel(Parcel dest, int flags) {
    dest.writeString(name());
    dest.writeInt(numberOfLegs());
    dest.writeList(countries());
  }

  @Override
  public int describeContents() {
    return 0;
  }
}
```

Note: If I keep ImmutableSet and Set it compiles successfully.

Appreciate help to resolve this issue.

**Comment by JakeWharton** [comment]
Did you add a type adapter for `ImmutableList`? this type isn't supported by default by this extension.

**Comment by ashraffouad** [comment]
No, can u clarify more what should be done?

**Comment by JakeWharton** [comment]
`ImmutableList` isn't supported by default and requires a type adapter to be registered: https://github.com/rharter/auto-value-parcel#typeadapters. #105 proposes supporting these by default, however, as normal AutoValue does.

**Comment by ashraffouad** [comment]
Thanks for clarification. It seems @xinthink has done great job of adding the support, is there any planned for its release to be included?

**Comment by hk0i** [comment]
Is there a good short term solution until #105 gets resolved? I understand how to do this for simple types but since ImmutableList would use generics I'm a little unsure?

For example, `inParcel.readArrayList()` requires a class loader, and I'm not sure how to supply that.
For illustrative purposes, this is what I tried that isn't working out for me:

```java
public class ImmutableListAdapter<T> implements TypeAdapter<ImmutableList<T>> {

    private final Class className;

    public ImmutableListAdapter(Class className) {
        this.className = className;
    }

    @Override
    public ImmutableList fromParcel(final Parcel in) {
        return ImmutableList.copyOf(in.readArrayList(className.getClassLoader()));
    }

    @Override
    public void toParcel(final ImmutableList value, final Parcel dest) {
        dest.writeList(value);
    }
}
```

Then in my `@AutoValue` class:

```java
    @ParcelAdapter(ImmutableListAdapter.class) // no way to properly annotate this field
    @Nullable
    public abstract String groupName();
```

**Comment by hk0i** [comment]
Scrap that, this was more of an android question rather than AutoValue specific, trying to do this in a regular class with Parcelable has the exact same issue, I use this for now:

```java
public final class ImmutableListTypeAdapter implements TypeAdapter<ImmutableList> {
    @SuppressWarnings("unchecked")
    @Override
    public ImmutableList fromParcel(final Parcel in) {
        return ImmutableList.copyOf(
            Objects.requireNonNull(
                in.readArrayList(
                    getClass().getClassLoader())));
    }

    @Override
    public void toParcel(final ImmutableList value, final Parcel dest) {
        dest.writeList(value);
    }
} 
```

**Comment by rharter** [comment]
That's how I'd do it for now. As @JakeWharton said, there been talk of
adding native support for guava collections, but no work yet. PRs are
welcome.
