### ISSUE TITLE
Emit type-specific writeXxx method calls instead of writeValue.

### ISSUE THREAD

**Issue by JakeWharton** [rharter/auto-value-parcel#12]
Calling `writeValue` is the easy thing to do, but it's not as efficient as it could be. When you have a `long` there's no need to round-trip through boxing. When you have a `Parcelable` (or subtype) there's no need to do the giant `instanceof` dance inside of `writeValue`.

**Comment by JakeWharton** [comment]
Also, obviously, the same for reading values as well. Unless the type itself is `Object` (is that even supported, actually?) we should know what method to call statically.

**Comment by rharter** [comment]
That's a good point.  One issue, for boxed types, at least, is that they could be null (though we know that at compile time via `@Nullable`).  `[read|write]Value()` handles null values.  Perhaps I just use the value methods when the object is nullable.

**Comment by JakeWharton** [comment]
All of the type-specific methods handle `null` automatically (assuming they take a reference not a primitive, of course). For the boxed primitives just using `writeObject` is a good compromise.

**Comment by rharter** [comment]
I've got this mostly in place, but wanted your input on a specific part.  

`Parcel` has support for types that aren't in all API levels, like `PersistableBundle`, `Size` and `SizeF`.  Any thoughts on how to deal with that?  I could leave those options out, but that wouldn't be very versatile.  Can I check the classpath at build time to ensure their availability?

**Comment by JakeWharton** [comment]
I don't think you need to do anything special. You wouldn't be able to use those types in the `@AutoValue`-annotated class anyway without lint yelling at you and requiring `@TargetApi` declaration (which is acknowledgement of their minimum API requirement).

**Comment by rharter** [comment]
Ahh, good point.  And it wouldn't be in the generated code if not used in the `@AutoValue`-annotated class, so it's a non-issue.
