### ISSUE TITLE
Ignore properties from parcelable

### ISSUE THREAD

**Issue by DevAhamed** [rharter/auto-value-parcel#122]
Hi,

Is there a way properties can be excluded from parcelable implementation, such as add an annotation for a property to ignore it.

**Comment by JakeWharton** [comment]
Can you provide an example where this would be useful?

**Comment by rharter** [comment]
This would break the value class semantics, as value classes define
equality based on the value of their properties.  If you were to ignore
fields for serialization via Parcel, this would mean that the value object
that you get back after parceling and unparceling would not be equal to the
value object you put in.  For that reason, this doesn't make sense in this
context.

**Comment by DevAhamed** [comment]
@JakeWharton I am trying to implement the MVI pattern which you explained in one of your talks. I have some view state class which holds the data as well. While saving/restoring the activity i dont want the data to be added to parcelable. If you have any suggestions i will be glad.

@rharter I never thought in that context. I made the changes and about to make a PR (changes are still in my clone), but this changed the entire perspective. Even if i override the equals method, i think it would become kind of niche feature.

**Comment by DevAhamed** [comment]
I made few changes to the lib in my clone and now it works best for me. Thanks for this awesome library. I am gonna close this.
