### ISSUE TITLE
I keep getting the `javapoet` error 

### ISSUE THREAD

**Issue by dev-JE02** [rharter/auto-value-parcel#125]
I keep getting the same error when using `auto-value-parcel` and `auto-value-firebase`. The project works without adding their dependencies and usages. But when I add them back the problem returns. Please take a look at my `app/build.gradle` file

    apply plugin: 'com.android.application'
    apply plugin: 'me.tatarka.retrolambda'
    
    android {
        compileSdkVersion 26
        buildToolsVersion "26.0.1"
        defaultConfig {
            applicationId "PACKAGE"
            minSdkVersion 21
            targetSdkVersion 26
            versionCode 1
            versionName "1.0"
            testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        }
    
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8
        }
    
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
    
        packagingOptions {
            exclude 'META-INF/rxjava.properties'
        }
    }
    
    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        androidTestCompile 'com.google.code.findbugs:jsr305:3.0.1'
        androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
            exclude group: 'com.android.support', module: 'support-annotations'
        })
        testCompile 'junit:junit:4.12'
    
        // Android Support Libraries
        compile 'com.android.support:appcompat-v7:26.0.1'
        compile 'com.android.support.constraint:constraint-layout:1.0.2'
        compile 'com.android.support:design:26.0.1'
        compile 'com.android.support:recyclerview-v7:26.0.1'
        compile 'com.android.support:exifinterface:26.0.1'
    
        // JavaPoet
        annotationProcessor 'com.squareup:javapoet:1.8.0'
        provided 'com.squareup:javapoet:1.8.0'
    
        // Dagger 2
        compile 'com.google.dagger:dagger:2.4'
        provided 'javax.annotation:jsr250-api:1.0'
        annotationProcessor 'com.google.dagger:dagger-compiler:2.4'
    
        // AutoValue
        provided 'com.google.auto.value:auto-value:1.5'
        annotationProcessor 'com.google.auto.value:auto-value:1.5'
    
        // AutoParcel
        annotationProcessor 'com.ryanharter.auto.value:auto-value-parcel:0.2.5'
    
        // AutoValue Firebase
        annotationProcessor 'me.mattlogan.auto.value:auto-value-firebase:1.1.0'
        provided 'me.mattlogan.auto.value:auto-value-firebase-annotation:1.1.0'
    
        // Firebase
        compile 'com.google.firebase:firebase-database:11.4.0'
        compile 'com.google.firebase:firebase-auth:11.4.0'
        compile 'com.github.frangsierra:rx2firebase:1.1.3'
    
        // RxJava 2
        compile 'io.reactivex.rxjava2:rxjava:2.1.0'
        compile 'com.akaita.java:rxjava2-debug:1.2.0'
    
        // RxAndroid 2
        compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    
        // RxLifecycle 2
        compile 'com.trello.rxlifecycle2:rxlifecycle-android:2.0.1'
    
        // RxBinding 2
        compile 'com.jakewharton.rxbinding2:rxbinding:2.0.0'
    
        // Simple Stack
        compile 'com.github.Zhuinden:simple-stack:1.7.2'
    
        // Butterknife
        compile 'com.jakewharton:butterknife:8.4.0'
        annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'
    
        // Timber
        compile 'com.jakewharton.timber:timber:4.3.1'
    
        // SwipyRefreshLayout
        compile 'com.github.orangegangsters:swipy:1.2.3@aar'
    
        // Glide
        compile 'com.github.bumptech.glide:glide:4.1.1'
        annotationProcessor 'com.github.bumptech.glide:compiler:4.1.1'
    
        // Glide Transformations
        compile 'jp.wasabeef:glide-transformations:2.0.2'
    
        // Calligraphy
        compile 'uk.co.chrisjenx:calligraphy:2.2.0'
    
        // Lorem Ipsum Generator
        compile 'de.sven-jacobs:loremipsum:1.0'
    
        // Pretty Time
        compile 'org.ocpsoft.prettytime:prettytime:4.0.1.Final'
    
        // Flexible AdannotationProcessorers
        compile 'eu.davidea:flexible-adapter:5.0.0-rc2'
    
        // Animated Checkbox
        compile 'com.hanks.animatecheckbox:library:0.1'
    
        // EventBus
        compile 'org.greenrobot:eventbus:3.0.0'
    
        // Parceler
        compile 'org.parceler:parceler-api:1.1.6'
        annotationProcessor 'org.parceler:parceler:1.1.6'
    
        //PhotoView
        compile 'com.github.chrisbanes:PhotoView:2.0.0'
    
        // Android Image Cropper
        compile 'com.theartofdev.edmodo:android-image-cropper:2.4.4'
    
        // File Chooser
        compile 'com.droidninja:filepicker:2.0.8@aar'
    
        // Intl Phone Input
        compile 'net.rimoto:intlphoneinput:1.0.1'
    }
    
    
    apply plugin: 'com.google.gms.google-services'

**Comment by JakeWharton** [comment]
What error?

**Comment by dev-JE02** [comment]
Sorry, this error

`Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.NoSuchMethodError: com.squareup.javapoet.TypeName.isBoxedPrimitive()Z`

**Comment by JakeWharton** [comment]
That method was added in JavaPoet 1.7 and you're explicitly specifying 1.8. The only way this could happen is if you're getting an older version on the classpath. You can use the `dependencies` task to get a graph of the dependencies that are being used in the `annotationProcessor` configuration. Beyond that, any issue here is one with Gradle. You should create a small representative sample that demonstrates the problem and file a bug on Gradle.

**Comment by hzsweers** [comment]
Nothing further to act on here, important part is to make sure you're using the correct versions on the classpath
