### ISSUE TITLE
serialVersionUID not copied

### ISSUE THREAD

**Issue by emakar** [rharter/auto-value-parcel#126]
Hi! Auto-value-parcel won't copy superclass' `serialVersionUID`, however this is expected as per https://github.com/google/auto/blob/e478e72237da795931c3813034b824cac4abf184/value/userguide/howto.md#-make-my-class-java--or-gwt-serializable
Also it causes unexpected behaviour (commonly met with absent `serialVersionUID` which is a case)
Thanks

**Comment by hzsweers** [comment]
I believe this is an autovalue issue, not the parcelable implementation. serialVersionUID seems like something that shouldn't be in the intermediary class. Feel free to comment if you disagree though!
