### ISSUE TITLE
Adding auto value parcel is causing a strange dependency error on auto value

### ISSUE THREAD

**Issue by atrich-ms** [rharter/auto-value-parcel#127]
I'm trying to add auto-value-parcel to my gradle like so:

    dependencies {
    ...

    // Google auto value
    compileOnly "com.google.auto.value:auto-value:1.5"
    annotationProcessor         "com.google.auto.value:auto-value:1.5"

    // Auto value parcelable extension
    annotationProcessor 'com.ryanharter.auto.value:auto-value-parcel:0.2.6'

    // Auto value Gson extension
    annotationProcessor 'com.ryanharter.auto.value:auto-value-gson:0.6.0'
    compileOnly 'com.ryanharter.auto.value:auto-value-gson-annotations:0.6.0'
    implementation 'com.google.code.gson:gson:2.8.0'

But this is resulting in an error:
> Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.
    - auto-value-1.5.jar (com.google.auto.value:auto-value:1.5)
  Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
  See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.

However, I already have an annotationProcessor configuration for com.google.auto.value:auto-value:1.5, so I'm not sure why I'm getting this error. Any thoughts?

**Comment by JakeWharton** [comment]
Remove
```groovy
compileOnly "com.google.auto.value:auto-value:1.5"
```
and replace it with
```groovy
compileOnly 'com.jakewharton.auto.value:auto-value-annotations:1.5'
```

**Comment by atrich-ms** [comment]
That was it! Thanks.

Should I replace `compileOnly "com.google.auto.value:auto-value:1.5"` with the com.jakewharton version everywhere in my project? What is the difference between these two dependency settings?

**Comment by JakeWharton** [comment]
The latter only includes the annotations. The former includes the
annotation processor, which the Android Gradle plugin detects and warns you
about despite the fact that you have it duplicated onto the
annotationProcessor classpath.

And yes, it's safe to use this everywhere.

**Comment by atrich-ms** [comment]
Great, thanks!
