### ISSUE TITLE
Don't generate null-check for fields with no nullity annotations

### ISSUE THREAD

**Issue by m-sasha** [rharter/auto-value-parcel#130]
I have a class with two fields, of which exactly one holds a non-null value. I would prefer to not mark them as @Nullable, as that will create a mild annoyance in a context where is it known which of the two values is non-null. Unfortunately, auto-value-parcel adds an explicit null-check in the constructor of types whose getter is not marked as @Nullable.

I would prefer is the null-check was added only for fields explicitly marked as @NonNull.

**Comment by JakeWharton** [comment]
This is the behavior of AutoValue, not this extension.

**Comment by JakeWharton** [comment]
Also you should make those two fields a nested @AutoOneOf

**Comment by m-sasha** [comment]
Oops, sorry. I had a reason to believe auto-value-parcel does this, but it was wrong.
