### ISSUE TITLE
Release incremental support

### ISSUE THREAD

**Issue by Laimiux** [rharter/auto-value-parcel#137]
Support for incremental annotation processing has been added a while ago to this processor. Could you release a new version with it? cc @rharter

**Comment by pjakubczyk** [comment]
Yep. That'd great ...
I tried to use jitpack but I'm not 100% sure if `auto_value_parcel_adapter` is properly set

**Comment by stojan26** [comment]
Any updates on this one? Can we do anything to help?

**Comment by rharter** [comment]
I've been on parental leave, so haven't been able to get to this. I'd like to get as many of the issues as I can cleared up in the coming weeks so that we can ship a stable final release of this.

**Comment by pjakubczyk** [comment]
any updates on this one?

**Comment by obs182** [comment]
I believe 0.2.7 supports incremental compilation already.
These are the [commits](https://github.com/rharter/auto-value-parcel/compare/0.2.6...master) between 0.2.6 and 0.2.7 and more specifically [this](https://github.com/rharter/auto-value-parcel/commit/8d84eec90d135f2eeb5b998eb9e1335b1fc3935a) one

**Comment by rharter** [comment]
This has been released in 0.2.7.
