### ISSUE TITLE
Custom Type Adapters

### ISSUE THREAD

**Issue by ming13** [rharter/auto-value-parcel#22]
Basically the same thing Gson and Moshi provide—the support for writing and reading custom not-first-hand-supported types using `Parcel`, such as `boolean`, `Date`, `Map<String, Set<String>>` and what not.

This is a proposed example for such type adapters.

```java
public final class DateAdapter implements Adapter<Date>
{
    @Override
    public void writeToParcel(@NonNull Parcel parcel, @NonNull Date date) {
        parcel.writeLong(date.getTime());
    }

    @Override
    public Date readFromParcel(@NonNull Parcel parcel) {
        return new Date(parcel.readLong());
    }
}
```

**Comment by rharter** [comment]
This is an interesting idea.  I think something like this makes a lot of sense given you always could parcel unparcelable types, you just had to do it manually.

I think the main difference here from Gson and Moshi is that in each of those, you register the type adapter with the instance that you're using to de/serialize, whereas with Parcelable there is no such instance.  

One option might be to provide an annotation on the method in question providing the adapter:

```java
@AutoValue public abstract class Foo {
  public String bar();
  @Adapter(DateAdapter.class) public Date baz();
}
```

Thinking through that, that would add a small runtime dependency to the project to hold the `Adapter` interface, but that could be done in a separate, optional, dependency.  That does kind of become an extension to an extension, though.  Another option would be to dynamically generate the class if it's being used, but that could cause problems with `provided` vs. `apt` scoping.

I'd be interested to hear your thoughts on this.

**Comment by JakeWharton** [comment]
Both Gson and Moshi support defining adapters on fields exactly the same
way, so there's precedence there.

**Comment by ming13** [comment]
Yep, there is no direct `Parcelable` manager where we can register `Adapter` instances. I think the proposed annotation-based solution is the way to go—mostly because there are no other ways. This has a drawback though—if there is a million `Date` fields we have to set a million annotations.

**Comment by rharter** [comment]
You guys think the optional runtime dependency is also the way to go?

**Comment by JakeWharton** [comment]
Yep! Just an iterface and an annotation, right?

**Comment by rharter** [comment]
I think it's just the interface, as the annotation can have source
retention to just be used for generation, right?

**Comment by JakeWharton** [comment]
Yeah. But presumably it's in the same artifact with the interface so it can
be referenced in code.

**Comment by rharter** [comment]
Cool, I got it started, I'll get a PR up probably on Monday due to holiday
plans, but we'll see.
