### ISSUE TITLE
Parcelable subinterfaces reported as not supported Parcelable type

### ISSUE THREAD

**Issue by jush** [rharter/auto-value-parcel#37]
I have the following class:
```Java
import com.google.android.gms.maps.model.LatLng;
...
@AutoValue
public abstract class RouteSegment implements Parcelable {
    public abstract LatLng startPoint();
    public abstract LatLng endPoint();
    ...
}
```

[LatLng](https://developers.google.com/android/reference/com/google/android/gms/maps/model/LatLng) is provided by Google Maps Android API which implements `SafeParcelable` which in turn extends `Parcelable`.

Since `LatLng` implements `Parcelable` I expected it to be handled properly without the need for a `TypeAdapter`.

**Comment by rharter** [comment]
I would, too. What are you seeing differently?

**Comment by rharter** [comment]
I see from your other issue that it's just acting like it's not parcelable. My suspicion is that the parcelable interface check isn't recursive. I'll take a look this morning.
