### ISSUE TITLE
Warning when compiling `Parcelable` classes

### ISSUE THREAD

**Issue by menny** [rharter/auto-value-parcel#40]
_AutoValue_ is complaining about having abstract methods which are not properties or Builders:
`warning: @AutoValue classes cannot have abstract methods other than property getters and Builder converters`

Since we are using "-Werror" compiler options (we are strict about compiler warnings in our code), the compilation will fail.

Is there a way around this warning?

Thanks

**Comment by rharter** [comment]
This is a [known issue](https://github.com/google/auto/issues/286) in AutoValue, and already has a [Pull Request](https://github.com/google/auto/pull/299) waiting to be merged that fixes it.  Unfortunately, until this PR is merged and released, the only work around is to build your own internal AutoValue that includes this pull request.  Also, feel free to comment on the pull request to share your support for fixing the issue ;)
