### ISSUE TITLE
BadParcelableException in Robolectric unit-tests

### ISSUE THREAD

**Issue by menny** [rharter/auto-value-parcel#42]
Seems like [Robolectric](https://github.com/robolectric/robolectric) doesn't like the class hierarchy Auto-Value outputs.

I have an example project that shows this:
https://github.com/menny/auto-value-parcel-robolectric/tree/master

`MainActivity` has three static method:
1. `testParcel` - which shows AutoValue-Parcel usage.
2. `testParcel2` - which creates the same class hierarchy manually.
3. `testParcelC` - which has a single class that declare the Parcelable interface and implements it.

When running on device, all three methods run without any exception, or errors.
When running a Robolectric unit-test `testParcel` and `testParcel2` will fail with `BadParcelableException`, while testParcelC passes.

The exception stack-trace is:
```
android.os.BadParcelableException: IllegalAccessException when unmarshalling: com.example.menny.roboautovalue.AutoValue_TestModel
    at android.os.Parcel.readParcelableCreator(Parcel.java:2099)
    at android.os.Parcel.readParcelable(Parcel.java:2055)
    at com.example.menny.roboautovalue.TestModelTest.testParcel(TestModelTest.java:22)
```

I also opened an issue at Robolectric: https://github.com/robolectric/robolectric/issues/2398, but I would love some insight into this.

**Comment by GrahamRogers** [comment]
Is there any update on this? It's blocking us using this awesome project.

**Comment by rharter** [comment]
I'm closing this as it is a Robolectric issue tracked by issue [robolectric/robolectric#2398](https://github.com/robolectric/robolectric/issues/2398).

**Comment by eamonnmcmanus** [comment]
I think the specific issue here is that com.example.menny.AutoValue_TestModel.CREATOR is not accessible from other packages, because AutoValue_TestModel is not public. This is apparently a difference in behaviour between the Robolectric environment and the real Android environment.

Perhaps the generated class could be public if the original `@AutoValue` class is public? That would give people a way to work around this problem, and I don't think it would compromise security.

**Comment by menny** [comment]
@eamonnmcmanus this will definitely fix the issue, but it also pollutes the public visible namespace. Also, it will not solve the issue when the original `@AutoValue` class is package-protected (which is a popular developer preference in our organization).

The cause of the issue is that Sun's JVM 1.8 introduced a `Caller` check to disallow reflection calls from callers that are not in the same package. Android's JVM does not do this assertion.
