### ISSUE TITLE
error: AutoValue property <drawable> is not a supported Parcelable type.

### ISSUE THREAD

**Issue by Rainer-Lang** [rharter/auto-value-parcel#43]
I get this error after switching from https://github.com/frankiesardo/auto-parcel to this lib for a test.
Do I have to implement a TypeAdapter?

**Comment by JakeWharton** [comment]
Yes, or change the type (e.g., store the drawable resource ID not the drawable itself).

**Comment by Rainer-Lang** [comment]
@JakeWharton Thanks.
Any plans to support some default TypeAdapters (like Date, Calendar, Drawable,...) in the lib or adapter-extension?

**Comment by JakeWharton** [comment]
Drawable can't be supported. Date and Calendar are already Serializable
which works in a Parcel already.

**Comment by Rainer-Lang** [comment]
@JakeWharton OK, fine. Thanks again.
I close this issue.
