### ISSUE TITLE
Complete Builder support

### ISSUE THREAD

**Issue by konmik** [rharter/auto-value-parcel#49]
https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#-initialize-a-builder-to-the-same-property-values-as-an-existing-value-instance

When I write `public abstract Builder toBuilder();` AutoValue generates a builder but auto-value-parcel says "Error:(23, 29) error: AutoValue property toBuilder is not a supported Parcelable type."

The correct behavior would be to check if the method returns a value that is a builder then skip it from parceling.

**Comment by gabrielittner** [comment]
That's a known issue in Auto Value https://github.com/google/auto/issues/281
