### ISSUE TITLE
Can't include lib snapshot into Android app project

### ISSUE THREAD

**Issue by felipecsl** [rharter/auto-value-parcel#5]
I'm getting this error after including this lib into an android app project:

```
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.UnsupportedClassVersionError: com/ryanharter/auto/value/parcel/AutoValueParcelExtension : Unsupported major.minor version 52.0
```

build.gradle:
`compile 'com.google.auto.value:auto-value:1.2-SNAPSHOT'`

I tried cloning the repo and building myself on Java 7 and surprisingly it compiled fine (except for one test that failed for some reason). Maybe you built it with Java 8 when you uploaded to Sonatype? Could that be the reason for this error?

**Comment by rharter** [comment]
@felipecsl I've just updated the released snapshot.  Double check that this works for you.

**Comment by felipecsl** [comment]
worked. thanks!
