### ISSUE TITLE
Non-compilable code is generated when 2 TypeAdapters of the same class name, but different namespaces are used.

### ISSUE THREAD

**Issue by frenchdonuts** [rharter/auto-value-parcel#52]
Good day,

I have 2 TypeAdapters, EditHybridStations.HybridStation.ListTypeAdapter and GetParentStationsAll.Station.ListTypeAdapter used as ParcelAdapters for another AutoValue class, GetParentStationsAll.Response. The generated code is:
```
public AutoValue_GetParentStationsAll_Response createFromParcel(Parcel in) {
  EditHybridStations.HybridStation.ListTypeAdapter listTypeAdapter = new EditHybridStations.HybridStation.ListTypeAdapter();
  GetParentStationsAll.Station.ListTypeAdapter listTypeAdapter = new GetParentStationsAll.Station.ListTypeAdapter();
  return new AutoValue_GetParentStationsAll_Response(
      listTypeAdapter.fromParcel(in),
      listTypeAdapter.fromParcel(in)
  );
}
```
As you can see, there are 2 variables named listTypeAdapter within the same scope. The same bug occurs also for the corresponding writeToParcel method.

**Comment by rharter** [comment]
Good catch. For now, you should be able to fix it by altering a class name, but this can b fixed shortly.
