### ISSUE TITLE
Compilation fails when using AutoValue's `toBuilder`

### ISSUE THREAD

**Issue by toadzky** [rharter/auto-value-parcel#56]
Error message is: 
`Error:(33, 27) error: AutoValue property toBuilder is not a supported Parcelable type.`

Is there a way to ignore a field for parceling? Something like https://github.com/square/auto-value-redacted?

**Comment by rharter** [comment]
This is a known issue in AutoValue, itself.  Check this issue for the workaround: https://github.com/google/auto/issues/281

**Comment by toadzky** [comment]
Thanks
