### ISSUE TITLE
Boxed primitives are stored as Serializable

### ISSUE THREAD

**Issue by jarettmillard** [rharter/auto-value-parcel#57]
Given this:
```
public abstract Integer foo();
```
The plugin generates this:
```
dest.writeSerializable(foo());
```

**Comment by rharter** [comment]
What are you expecting to see here?  `Integer` is serializable, so this makes sense.  It can't be stored as a primitive, since it could be null.

**Comment by JakeWharton** [comment]
It's already `null` checked so storing the primitive would be safe.

**Comment by rharter** [comment]
Unless it's `@Nullable`.  Is there a benefit to coercing them to primitives iff they're a non-nullable boxed primitive?

**Comment by jarettmillard** [comment]
Thanks guys!
