### ISSUE TITLE
Doesn't work with auto-value-moshi

### ISSUE THREAD

**Issue by johnkil** [rharter/auto-value-parcel#65]
Сan generate the code for AdapterFactory. 
auto-value-parcel v0.3.2
auto-value-parcel v0.2.2

stacktrace:
>Error:(10, 39) error: package com.ryanharter.auto.value.moshi does not exist
>Warning:@AutoValue classes cannot have abstract methods other than property getters and Builder converters
>Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.NoSuchMethodError: com.squareup.javapoet.TypeName.isBoxedPrimitive()Z

**Comment by rharter** [comment]
This appears to duplicate #64
