### ISSUE TITLE
Identifier expected

### ISSUE THREAD

**Issue by konmik** [rharter/auto-value-parcel#79]
Hi :)

Here is the source file:

``` java
@AutoValue
public abstract class CurrencyViewState implements ViewState {
    public abstract CurrencyInfo currency();
    public abstract Transient<SolidList<CurrencyInfo>> currencies();
```

Here is the generated class:

``` java
final class AutoValue_CurrencyViewState extends $AutoValue_CurrencyViewState {
  public static final Parcelable.Creator<AutoValue_CurrencyViewState> CREATOR = new Parcelable.Creator<AutoValue_CurrencyViewState>() {
    @Override
    public AutoValue_CurrencyViewState createFromParcel(Parcel in) {
      return new AutoValue_CurrencyViewState(
          (CurrencyInfo) in.readParcelable(CurrencyInfo.class.getClassLoader()),
          (Transient<SolidList<CurrencyInfo>>) in.readParcelable(SolidList<T>.class.getClassLoader())
      );
    }
    @Override
    public AutoValue_CurrencyViewState[] newArray(int size) {
      return new AutoValue_CurrencyViewState[size];
    }
  };
```

Please take a look at: `SolidList<T>.class.getClassLoader()`.

It causes the compilation error: "Error:(16, 79) error: <identifier> expected"

Is there a quick fix possible from your side or it will be quicker for me to clone/explore/fix/push?

**Comment by codebutler** [comment]
I ran into this too and did some digging. The behavior changed in e5e334f022cac606d48cd5d1fcb15d42fae4779b and there isn't sufficient error checking. It will generate bad code if you forget to make one of your types `implement Parcelable`.

**Comment by rharter** [comment]
Hey @konmik! Yeah, I think this should be a fairly easy fix, just checking if the parcelable type is parameterized and handling it appropriately. I'll take a look once I get to the airport.
