### ISSUE TITLE
Must be final

### ISSUE THREAD

**Issue by f2prateek** [rharter/auto-value-parcel#83]
Just wondering if/why this extension needs to be run last.

Relevant LOC:
https://github.com/rharter/auto-value-parcel/blob/master/auto-value-parcel/src/main/java/com/ryanharter/auto/value/parcel/AutoValueParcelExtension.java#L117-L120

**Comment by rharter** [comment]
Because Parcel uses a static `CREATOR`, and `$AutoValue_Foo.CREATOR` is different than `AutoValue_Foo.CREATOR`.

**Comment by f2prateek** [comment]
Oh I see, thanks!
