### ISSUE TITLE
Unnecessary null check code for List 

### ISSUE THREAD

**Issue by niqo01** [rharter/auto-value-parcel#84]
It seams that for `List<Something>` the generated code look like this:
```
     in.readInt() == 0 ? (List<Something>) in.readArrayList(cl) : null,
     ...
    if (items() == null) {
      dest.writeInt(1);
    } else {
      dest.writeInt(0);
      dest.writeList(items());
    }
```
but `readArrayList` and `writeList` Android code already handle the null case. See https://developer.android.com/reference/android/os/Parcel.html#readArrayList(java.lang.ClassLoader)

**Comment by JakeWharton** [comment]
On it.

**Comment by JakeWharton** [comment]
There's a few of these actually which I added support for in #85. But there's a bunch more supported but not documented for which I filed http://b.android.com/221343.
