### ISSUE TITLE
Global/implicit TypeAdapters

### ISSUE THREAD

**Issue by skylve** [rharter/auto-value-parcel#86]
`TypeAdapter`s abstraction is really nice but can be a pain when you need to write `@ParcelAdapter(XXX.class)` every time for the same type in every definition.

Would it be possible to add something like Global / Implicit TypeAdapters like :

``` java
@ImplicitParcelAdapter(Date.class)
public class DateTypeAdapter implements TypeAdapter<Date> { ... }
```

That would be resolved at compile time to append to the list of supported type adapters ?

**Comment by ZacSweers** [comment]
Going to close this one out. This opens a pretty significant can of worms for managing conflicting definitions, nor would it work across compilation boundaries.
