### ISSUE TITLE
Error adding Action0 as autovalue attribute.

### ISSUE THREAD

**Issue by epool** [rharter/auto-value-parcel#88]
I want to use [Action0](http://reactivex.io/RxJava/javadoc/rx/functions/Action0.html) as a field of my auto value class that implements `Parcelable`, but I am getting this error:

```
Note: Generating a MembersInjector for com.mdlive.mdlcore.activity.core.MdlCoreActivity. Prefer to run the dagger processor over that class instead.
MdlDialogScreenKey.java:36: error: AutoValue property positiveAction is not a supported Parcelable type.
    public abstract Action0 positiveAction();
```

I have needed to create a mixed interface as a workaround:

```
public interface MyAction0 extends Action0, Serializable {}
```

Is this behavior planned to be supported by `auto-value-parcel`?

**Comment by rharter** [comment]
`Action0` isn't a Parcelable type, so it can't be included in a Parcelable. That's not a bug. 

Even with your work around, how exactly is the action to be reconstructed.

**Comment by epool** [comment]
@rharter Thanks!
