### ISSUE TITLE
AIDL: CREATOR cannot be resolved or is not a field

### ISSUE THREAD

**Issue by autonomousapps** [rharter/auto-value-parcel#91]
I'm attempting to use this extension because I want to pass an AutoValue-annotated class across a process boundary with AIDL. Project [here](https://bitbucket.org/tonyrobalik/reactivestopwatch), specific commit demonstrating issue [here](https://bitbucket.org/tonyrobalik/reactivestopwatch/commits/8dacdd5dd9c928ffd146ef5889e8bf7d590fcc8d).

It's possible I'm simply not using something correctly.

When I run `./gradlew assembleDebug`, I get the following error:

```
ERROR: /workspace/ReactiveStopwatch/app/build/generated/source/aidl/debug/com/autonomousapps/reactivestopwatch/service/IStopwatchService.java:172: CREATOR cannot be resolved or is not a field
```

The generated IStopwatchService.java class has this line:

``` java
_result = com.autonomousapps.reactivestopwatch.time.Lap.CREATOR.createFromParcel(_reply);
```

Which might be the problem. After all, `Lap` doesn't have that field. `AutoValue_Lap`, however, does. I could change all my implementations to use the latter instead of the former, but that seems to be against the spirit of the thing.

Here's my AutoValue-annotated class:

``` java
package com.autonomousapps.reactivestopwatch.time;

@AutoValue
public abstract class Lap implements Parcelable {

    public static Lap create(long duration, long endTime) {
        return new AutoValue_Lap(duration, endTime);
    }

    abstract long duration();

    abstract long endTime();
}
```

AIDL definition:

``` java
package com.autonomousapps.reactivestopwatch.time;

parcelable Lap;
```

Use in other AIDL file:

``` java
package com.autonomousapps.reactivestopwatch.service;

import com.autonomousapps.reactivestopwatch.time.Lap;

interface IStopwatchService {
    // other methods omitted
    Lap lap();
}
```

**Comment by rharter** [comment]
If you want to call the CREATOR directly you are correct, you would have to use the implementation, as opposed to the abstract class. You are also correct that that is kind of against the spirit of how it's intended to be used (exposing implementation detail).

I think normally you would use the Parcel's `getParcelable` and `putParcelable` methods, and it will resolve the types automatically and return the (subclass implementation of) your Lap class.

**Comment by autonomousapps** [comment]
Unfortunately, `IStopwatchService.java` is auto-generated from its AIDL file, and I don't know if how it does that is configurable.

I'm not really sure what you mean about `getParcelable` and `putParcelable`. Like I said, I'm relying on the build system to generate these files, and I'm actually doing nothing with the parceling myself (at least not directly).

Is there some way I could declare the `CREATOR` field in the abstract class, but let its implementation be taken care of by the subclass? Not even sure if that would work... perhaps AIDL just doesn't play nicely with this use case?

**Comment by JakeWharton** [comment]
You could probably put

public static final Creator<Lap> CREATOR = AutoValue_Lap.CREATOR;

in Lap and have it work as well.

**Comment by autonomousapps** [comment]
Just tried, here's the error message:

```
ERROR: /workspace/ReactiveStopwatch/app/src/main/java/com/autonomousapps/reactivestopwatch/time/Lap.java:19: Manual implementation of a static Parcelable.Creator<T> CREATOR field found when processing com.autonomousapps.reactivestopwatch.time.Lap. Remove this so auto-value-parcel can automatically generate the implementation for you.
```

Android Studio is also complaining that it's an incompatible assignment [screen cap](https://www.dropbox.com/s/l7x8tnj6j0y7to5/Screen%20Shot%202016-10-02%20at%2010.48.27%20AM.png?dl=0).

I tried replacing the declaration like so:

```
public static final Creator<AutoValue_Lap> CREATOR = AutoValue_Lap.CREATOR;
```

but then it failed with this error:

```
* What went wrong:
Execution failed for task ':app:transformJackWithJackForDebug'.
> com.android.jack.ir.JNodeInternalError: Error building Jack IR: com.android.jack.eclipse.jdt.internal.compiler.ast.TypeDeclaration at "/workspace/ReactiveStopwatch/app/build/generated/source/apt/debug/com/autonomousapps/reactivestopwatch/ui/StopwatchFragment_ViewBinding.java:15.14-15.42"
```

**Comment by autonomousapps** [comment]
If it's helpful, Gradle build scan: https://scans.gradle.com/s/pw6wdwaifuce2

**Comment by JakeWharton** [comment]
Ah, yeah we forbid you from trying to define your own creator.

**Comment by autonomousapps** [comment]
Yeah, I thought so (from a cursory review of other issues). Is that a restriction we can loosen?

**Comment by JakeWharton** [comment]
We could enable the use of @SuppressWarning to skip it.

**Comment by autonomousapps** [comment]
I'd be willing to test an experimental branch or binary.

**Comment by autonomousapps** [comment]
I can also take a stab at a PR for the issue.

**Comment by autonomousapps** [comment]
Closing the loop: https://code.google.com/p/android/issues/detail?id=224466

**Comment by rharter** [comment]
I've filed this bug with the tools team.

https://code.google.com/p/android/issues/detail?id=224480

**Comment by atrich-ms** [comment]
Is there no action on this? Any workarounds? I'm having to port a codebase with a lot of autovalue types into an android service, and this issue is preventing me from making my types parcelable.

I attempted to use the AutoValue_ version of the type, but that type is defined as internal to the package it's declared in.

**Comment by ysyyork** [comment]
Yeah any updates on this?

**Comment by ZacSweers** [comment]
Nothing to be done here, can revisit if the above issues make progress

**Comment by chris-tate** [comment]
This is basically a showstopper for being able to use `auto-value-parcel` generally.  This one error genuinely confused me:

> Manual implementation of a static Parcelable.Creator CREATOR field found when processing com.autonomousapps.reactivestopwatch.time.Lap. Remove this so auto-value-parcel can automatically generate the implementation for you.

...because `auto-value-parcel` does *not* actually generate `Lap.CREATOR` as described.

In practice, JakeWharton's earlier note about making it possible to directly annotate to suppress this specific warning/error, meaning "yes i know this is an issue, but I know that I'm not doing any other subclassing or customization that breaks the general case", is all it would take to solve the 90% situation where I'm being forced to hand-write everything.

Failing that, it would be fantastic to have an annotation to suppress `auto-value-parcel` for a specific class, so we can write the marshaling code by hand while still using `@AutoValue` for everything else.  Right now, just having `auto-value-parcel` in my project means that it *must* be active for any `@AutoValue` class that implements `Parcelable`.
