### ISSUE TITLE
Generic bounds checking fails when bound is not Parcelable but declared type is.

### ISSUE THREAD

**Issue by JakeWharton** [rharter/auto-value-parcel#96]
``` java
interface Foo {}
interface Bar<F extends Foo> {
  F foo();
}
@AutoValue abstract class PFoo implements Foo, Parcelable {}
@AutoValue abstract class PBar implements Bar<PFoo>, Parcelable {}
```

```
Bar.java:340: error: AutoValue property foo is not a supported Parcelable type.
    F foo();
      ^
PBar:11: error: @AutoValue processor threw an exception: com.ryanharter.auto.value.parcel.AutoValueParcelException
@AutoValue public abstract class PBar implements Bar<PFoo>,
                           ^
        at com.ryanharter.auto.value.parcel.AutoValueParcelExtension.validateProperties(AutoValueParcelExtension.java:279)
        at com.ryanharter.auto.value.parcel.AutoValueParcelExtension.generateClass(AutoValueParcelExtension.java:158)
        at com.google.auto.value.processor.AutoValueProcessor.writeExtensions(AutoValueProcessor.java:474)
        at com.google.auto.value.processor.AutoValueProcessor.processType(AutoValueProcessor.java:460)
        at com.google.auto.value.processor.AutoValueProcessor.process(AutoValueProcessor.java:150)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
```

Looks like the implementation is resolving the bounds and trying to verify they are parcelable which fails, except that the generic was given a concrete type on the implementation class.

AV 1.3, extension 0.2.5

**Comment by ZacSweers** [comment]
Realized the solution for https://github.com/rharter/auto-value-gson/pull/241 can be used for this problem as well. PR here: #150

**Comment by luis9529** [comment]
> ```java
> interfaz  Foo {}
>  interfaz  Bar <F extiende  Foo > {
>    F  foo ();
> }
> @AutoValue  clase abstracta  PFoo implementa Foo , Parcelable {}
>  @AutoValue clase abstracta PBar implementa Bar < PFoo > , Parcelable {}        
> ```
> 
> ```
> Bar.java:340: error: AutoValue property foo is not a supported Parcelable type.
>     F foo();
>       ^
> PBar:11: error: @AutoValue processor threw an exception: com.ryanharter.auto.value.parcel.AutoValueParcelException
> @AutoValue public abstract class PBar implements Bar<PFoo>,
>                            ^
>         at com.ryanharter.auto.value.parcel.AutoValueParcelExtension.validateProperties(AutoValueParcelExtension.java:279)
>         at com.ryanharter.auto.value.parcel.AutoValueParcelExtension.generateClass(AutoValueParcelExtension.java:158)
>         at com.google.auto.value.processor.AutoValueProcessor.writeExtensions(AutoValueProcessor.java:474)
>         at com.google.auto.value.processor.AutoValueProcessor.processType(AutoValueProcessor.java:460)
>         at com.google.auto.value.processor.AutoValueProcessor.process(AutoValueProcessor.java:150)
>         at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
> ```
> 
> Parece que la implementación está resolviendo los límites y tratando de verificar que sean parcelables, lo que falla, excepto que al genérico se le dio un tipo concreto en la clase de implementación.
> 
> AV 1.3, extensión 0.2.5

**Comment by luis9529** [comment]
> ```java
> interfaz  Foo {}
>  interfaz  Bar <F extiende  Foo > {
>    F  foo ();
> }
> @AutoValue  clase abstracta  PFoo implementa Foo , Parcelable {}
>  @AutoValue clase abstracta PBar implementa Bar < PFoo > , Parcelable {}        
> ```
> 
> ```
> Bar.java:340: error: AutoValue property foo is not a supported Parcelable type.
>     F foo();
>       ^
> PBar:11: error: @AutoValue processor threw an exception: com.ryanharter.auto.value.parcel.AutoValueParcelException
> @AutoValue public abstract class PBar implements Bar<PFoo>,
>                            ^
>         at com.ryanharter.auto.value.parcel.AutoValueParcelExtension.validateProperties(AutoValueParcelExtension.java:279)
>         at com.ryanharter.auto.value.parcel.AutoValueParcelExtension.generateClass(AutoValueParcelExtension.java:158)
>         at com.google.auto.value.processor.AutoValueProcessor.writeExtensions(AutoValueProcessor.java:474)
>         at com.google.auto.value.processor.AutoValueProcessor.processType(AutoValueProcessor.java:460)
>         at com.google.auto.value.processor.AutoValueProcessor.process(AutoValueProcessor.java:150)
>         at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
> ```
> 
> Parece que la implementación está resolviendo los límites y tratando de verificar que sean parcelables, lo que falla, excepto que al genérico se le dio un tipo concreto en la clase de implementación.
> 
> AV 1.3, extensión 0.2.5

#150
