### ISSUE TITLE
Use bytes instead of ints as a boolean values

### ISSUE THREAD

**Issue by ansman** [rharter/auto-value-parcel#99]
I guess it's low priority but it would be beneficial if AVP wrote bytes instead of int to signal null values and when writing booleans.

Example:

Old:
```java
if (foo() == null) {
    dest.writeInt(1);
} else {
    dest.writeInt(0);
    dest.writeString(foo());
}
dest.writeInt(bar() ? 1 : 0);
```

Suggested change:
```java
if (foo() == null) {
    dest.writeByte((byte) 1);
} else {
    dest.writeByte((byte) 0);
    dest.writeString(foo());
}
dest.writeByte((byte) (bar() ? 1 : 0));
```

**Comment by ansman** [comment]
I'd be happy to make the change, if you approve.

**Comment by JakeWharton** [comment]
Writing bytes just writes ints: https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/os/Parcel.java#665

**Comment by ansman** [comment]
Wow, I guess I've been writing code for nothing for a year or so.
